# 本地資料庫環境
# 資料存放在目前目錄下的 data 裡
# 建議使用安裝了 Docker 擴充套件的 VSCode 開啟目錄，在本檔案上右鍵可以快速啟動、停止
# 如不需要相關容器開機自動啟動，可註釋掉 restart: always
# 如遇連線埠衝突，可調整 ports 下 : 前面的連線埠號
version: "3.1"

services:
  coolDB:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      --group_concat_max_len=102400
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai # 指定時區
      MYSQL_ROOT_PASSWORD: "123456" # 設定 root 使用者密碼
      MYSQL_DATABASE: "cool-crm" # 業務庫名
    networks:
      - cool
    ports:
      - 3307:3306

  coolRedis:
    image: redis
    #command: --requirepass "12345678" # Redis 庫密碼，不需要密碼註釋本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定時區
    volumes:
      - ./data/redis/:/data/
    networks:
      - cool
    ports:
      - 6380:6379

networks:
  cool: {}
