CREATE TABLE IF NOT EXISTS `crm_quote_invoice` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `createTime` varchar(255) NOT NULL COMMENT '建立時間',
  `updateTime` varchar(255) NOT NULL COMMENT '更新時間',
  `tenantId` int DEFAULT NULL COMMENT '租戶ID',
  `invoiceNo` varchar(50) NOT NULL COMMENT '發票ID',
  `quoteOrderId` int NOT NULL COMMENT '報價單ID',
  `quoteStageId` int NOT NULL COMMENT '付款階段ID',
  `quoteNo` varchar(50) DEFAULT NULL COMMENT '報價單編號',
  `quoteName` varchar(100) DEFAULT NULL COMMENT '專案名稱',
  `stageNo` int NOT NULL DEFAULT 1 COMMENT '付款階段',
  `stageName` varchar(100) DEFAULT NULL COMMENT '階段名稱',
  `ratio` decimal(8,4) NOT NULL DEFAULT 0.0000 COMMENT '付款比例',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '發票金額',
  `invoiceProductName` varchar(200) DEFAULT NULL COMMENT '開票產品',
  `seller` varchar(100) DEFAULT NULL COMMENT '賣方',
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `taxNumber` varchar(50) DEFAULT NULL COMMENT '統一編號',
  `email` varchar(100) DEFAULT NULL COMMENT '郵箱',
  `salesmanId` int DEFAULT NULL COMMENT '業務員ID',
  `applyUserId` int DEFAULT NULL COMMENT '申請人ID',
  `applyTime` varchar(30) DEFAULT NULL COMMENT '申請時間',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '狀態 1-待審核 2-已通過 3-已拒絕',
  `auditUserId` int DEFAULT NULL COMMENT '審核人ID',
  `auditTime` varchar(30) DEFAULT NULL COMMENT '審核時間',
  `auditRemark` varchar(255) DEFAULT NULL COMMENT '審核備註',
  `ecpayInvoiceNo` varchar(20) DEFAULT NULL COMMENT '綠界發票號碼',
  `ecpayInvoiceDate` varchar(30) DEFAULT NULL COMMENT '綠界發票日期',
  `ecpayRandomNumber` varchar(10) DEFAULT NULL COMMENT '綠界發票隨機碼',
  `ecpayIssueStatus` tinyint NOT NULL DEFAULT 0 COMMENT '綠界開票狀態 0-未開票 1-開票中 2-已開票 3-開票失敗',
  `ecpayIssueError` text DEFAULT NULL COMMENT '綠界開票失敗原因',
  `ecpayIssueTime` varchar(30) DEFAULT NULL COMMENT '綠界開票時間',
  `ecpayIssueResponse` text DEFAULT NULL COMMENT '綠界開票返回內容',
  `ecpayInvalidStatus` tinyint NOT NULL DEFAULT 0 COMMENT '綠界作廢狀態 0-未作廢 1-作廢中 2-已作廢 3-作廢失敗',
  `ecpayInvalidTime` varchar(30) DEFAULT NULL COMMENT '綠界作廢時間',
  `ecpayInvalidReason` varchar(255) DEFAULT NULL COMMENT '綠界作廢原因',
  `ecpayInvalidError` text DEFAULT NULL COMMENT '綠界作廢失敗原因',
  `ecpayInvalidResponse` text DEFAULT NULL COMMENT '綠界作廢返回內容',
  `autoSendEmail` tinyint NOT NULL DEFAULT 1 COMMENT '是否自動發送郵箱 0-否 1-是',
  `scheduledSendTime` varchar(30) DEFAULT NULL COMMENT '預計發送時間',
  `sendStatus` tinyint NOT NULL DEFAULT 0 COMMENT '郵件發送狀態 0-待發送 1-發送中 2-已發送 3-發送失敗',
  `sentTime` varchar(30) DEFAULT NULL COMMENT '郵件發送時間',
  `sendError` text DEFAULT NULL COMMENT '郵件發送失敗原因',
  `voidTime` varchar(30) DEFAULT NULL COMMENT '作廢時間',
  `isDeleted` tinyint NOT NULL DEFAULT 0 COMMENT '邏輯刪除 0-否 1-是',
  PRIMARY KEY (`id`),
  KEY `IDX_crm_quote_invoice_createTime` (`createTime`),
  KEY `IDX_crm_quote_invoice_updateTime` (`updateTime`),
  KEY `IDX_crm_quote_invoice_tenantId` (`tenantId`),
  KEY `IDX_crm_quote_invoice_invoiceNo` (`invoiceNo`),
  KEY `IDX_crm_quote_invoice_quoteOrderId` (`quoteOrderId`),
  KEY `IDX_crm_quote_invoice_quoteStageId` (`quoteStageId`),
  KEY `IDX_crm_quote_invoice_ecpayInvoiceNo` (`ecpayInvoiceNo`),
  KEY `IDX_crm_quote_invoice_ecpayIssueStatus` (`ecpayIssueStatus`),
  KEY `IDX_crm_quote_invoice_ecpayInvalidStatus` (`ecpayInvalidStatus`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='報價單發票記錄';

ALTER TABLE `crm_quote_order_stage`
  MODIFY COLUMN `invoiceStatus` tinyint NOT NULL DEFAULT 0 COMMENT '開票狀態 0-未申請 1-審核中 2-已作廢 3-已通過 4-已拒絕';

INSERT INTO `base_sys_param` (`keyName`, `name`, `data`, `dataType`, `remark`, `createTime`, `updateTime`)
SELECT
  'crmEcpayInvoice',
  'CRM綠界發票開票配置',
  '{"enabled":true,"env":"stage","mode":"b2b","merchantId":"2000132","hashKey":"ejCk326UnaZWKisg","hashIv":"q9jcZX8Ib9LM8wYk","endpoint":"https://einvoice-stage.ecpay.com.tw/B2BInvoice/Issue","invalidEndpoint":"https://einvoice-stage.ecpay.com.tw/B2BInvoice/Invalid","taxType":"1","invType":"07","itemWord":"項","timeout":15000}',
  0,
  '綠界 B2B 電子發票 Issue 配置；正式環境請改 env=prod、endpoint 改正式 B2B，並替換正式 MerchantID/HashKey/HashIV',
  NOW(),
  NOW()
WHERE NOT EXISTS (SELECT 1 FROM `base_sys_param` WHERE `keyName` = 'crmEcpayInvoice');
